# Generated by Django 3.2.6 on 2021-08-20 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Life', (('Daily', 'Daily'), ('RelationShip', 'RelationShip'), ('Family', 'Family'), ('Pets', 'Pets'), ('Hobby', 'Hobby'), ('Photography', 'Photography'), ('Cook', 'Cook'), ('Car', 'Car'), ('Interior', 'Interior'), ('Fashion/Beauty', 'Fashion/Beauty'), ('Health', 'Health'))), ('Travel/Restaurants', (('Domestic', 'Domestic'), ('Oversea', 'Oversea'), ('Camping/Hiking', 'Camping/Hiking'), ('Restaurants', 'Restaurants'), ('Cafe', 'Cafe'))), ('Entertainment', (('Tv', 'Tv'), ('Star', 'Star'), ('Movie', 'Movie'), ('Music', 'Music'), ('Book', 'Book'), ('Animation', 'Animation'), ('Exhibition', 'Exhibition'), ('Show', 'Show'), ('Craft', 'Craft'))), ('IT', (('IT Internet', 'IT Internet'), ('Mobile', 'Mobile'), ('Game', 'Game'), ('Science', 'Science'), ('IT Product', 'IT Product'))), ('Sports', (('Sports', 'Sports'), ('Soccer', 'Soccer'), ('Volleyball', 'Volleyball'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Golf', 'Golf'))), ('Current', (('Government', 'Government'), ('Society', 'Society'), ('Education', 'Education'), ('International', 'International'), ('Business', 'Business'), ('Economy', 'Economy'), ('Job', 'Job'))), ('Event', (('Event', 'Event'),))], max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
